### PR TITLE
fix submit execution dialog css

### LINKED ISSUE #185: Fix CSS for submit Execution page.
Need to update the submit execution dialog css

### PR DESCRIPTION
**Pull request by Rashmil-1999**

### CODE REVIEW

File: src/components/Execution/CreateExecutionDialog.tsx [hunk 1]
```diff
@@ -144,11 +144,16 @@ const CreateExecutionDialog = (props: CreateExecutionDialogProps) => {
...
                             Cancel
                         </Button>
                         <Button
-                            variant="solid"
+                            variant="outlined"
+                            sx={{
+                                borderColor: "primary.subtle",
+                                color: "primary.subtle",
+                                backgroundColor: "white"
+                            }}
```
Comment (longshuicy) [inline src/components/Execution/CreateExecutionDialog.tsx:153]: image

Don't you want to flip the "cancel" versus "submit" style? This looks like we are highlighting the "cancel" action.

Comment (Rashmil-1999) [reply src/components/Execution/CreateExecutionDialog.tsx:153]: ahh ... is it okay if I update this for all the dialogs in this PR then? I think I have it this way for some other dialogs too

Comment (longshuicy) [reply src/components/Execution/CreateExecutionDialog.tsx:153]: Yeah that will be great! Thank you :)

Comment (Rashmil-1999) [reply src/components/Execution/CreateExecutionDialog.tsx:153]: I have addressed this

**Review by longshuicy — APPROVED** [review]
LGTM
