### PR TITLE
81 implement dataset validation to inputs in submitting execution

### LINKED ISSUE #81: Implement dataset validation to inputs in Submitting Execution.
On the execution page, when a user is selecting the input datasets, We should enforce checks in the input so that we can stop the user from setting wrong dataset type to a input. To enforce these checks we can perhaps either get information from the datawolf tools or embed the information in the dependency graph.

### LINKED ISSUE #101: Show Datatype information on Execution page
The goal is to display Dataset type information on the execution create page and restrict only those datatype to be shown in the list.

### PR DESCRIPTION
**Pull request by Rashmil-1999**
This PR adds Dataset type information along with enforcement of dataset type for each field that can be selected at the execution create page.

### CODE REVIEW

File: src/components/AddAnalysisModal.tsx [hunk 1]
```diff
@@ -45,6 +46,7 @@ const AddAnalysisModal = ({ selectAnalysisModalOpen, setSelectAnalysisModalOpen
     const { addNodes } = useStore(useShallow(selector));
     const dependencyGraph = useAppSelector((state) => state.workflow.dependencyGraph);
     const datawolfTools = useAppSelector((state) => state.workflow.datawolfTools);
+    // const loading = useAppSelector((state) => state.workflow.loading);
```
Comment (longshuicy) [inline src/components/AddAnalysisModal.tsx]: This is no longer needed?

**Review by longshuicy — APPROVED** [review]
Looks good! I see the message validating inputs on each of the configuration. Approve.

File: src/components/AddAnalysisModal.tsx (hunk 1 above)
Comment (Rashmil-1999) [reply src/components/AddAnalysisModal.tsx]: ahh yes
